services:
  - type: web
    name: webdev-sample
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: DB_PATH
        value: /var/data/site.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
